-- =========================================================
-- FITZONE STORE
-- SEMANA 15
-- POSTGRESQL
-- PROYECTO INTEGRADOR
-- =========================================================


-- =========================================================
-- TABLA: USUARIOS
-- =========================================================

CREATE TABLE IF NOT EXISTS usuarios (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    usuario VARCHAR(50) NOT NULL UNIQUE,

    password VARCHAR(255) NOT NULL

);


-- =========================================================
-- TABLA: CLIENTES
-- =========================================================

CREATE TABLE IF NOT EXISTS clientes (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(80) NOT NULL,

    correo VARCHAR(120) NOT NULL UNIQUE,

    telefono VARCHAR(15) NOT NULL,

    ciudad VARCHAR(60) NOT NULL,

    activo BOOLEAN NOT NULL DEFAULT TRUE

);


-- =========================================================
-- TABLA: PROVEEDORES
-- =========================================================

CREATE TABLE IF NOT EXISTS proveedores (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(80) NOT NULL,

    productos VARCHAR(150) NOT NULL,

    contacto VARCHAR(30) NOT NULL,

    ciudad VARCHAR(60) NOT NULL,

    activo BOOLEAN NOT NULL DEFAULT TRUE

);


-- =========================================================
-- TABLA: PRODUCTOS
-- =========================================================
-- Cada producto puede estar relacionado con un proveedor.
-- =========================================================

CREATE TABLE IF NOT EXISTS productos (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre VARCHAR(80) NOT NULL,

    categoria VARCHAR(50) NOT NULL,

    descripcion VARCHAR(250) NOT NULL,

    stock INTEGER NOT NULL DEFAULT 0,

    proveedor_id INTEGER,

    CONSTRAINT fk_producto_proveedor
        FOREIGN KEY (proveedor_id)
        REFERENCES proveedores(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_producto_stock
        CHECK (stock >= 0)

);


-- =========================================================
-- TABLA: FACTURAS
-- =========================================================
-- Cada factura pertenece a un cliente.
-- =========================================================

CREATE TABLE IF NOT EXISTS facturas (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    numero VARCHAR(30) NOT NULL UNIQUE,

    fecha DATE NOT NULL,

    cliente_id INTEGER NOT NULL,

    forma_pago VARCHAR(50) NOT NULL,

    pagada BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_factura_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT

);


-- =========================================================
-- TABLA: DETALLE_FACTURA
-- =========================================================
-- Relaciona las facturas con los productos.
-- =========================================================

CREATE TABLE IF NOT EXISTS detalle_factura (

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    factura_id INTEGER NOT NULL,

    producto_id INTEGER NOT NULL,

    cantidad INTEGER NOT NULL,

    precio NUMERIC(10, 2) NOT NULL,

    CONSTRAINT fk_detalle_factura
        FOREIGN KEY (factura_id)
        REFERENCES facturas(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_detalle_producto
        FOREIGN KEY (producto_id)
        REFERENCES productos(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_detalle_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT chk_detalle_precio
        CHECK (precio > 0)

);


-- =========================================================
-- ÍNDICES PARA CLAVES FORÁNEAS
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_productos_proveedor
ON productos(proveedor_id);

CREATE INDEX IF NOT EXISTS idx_facturas_cliente
ON facturas(cliente_id);

CREATE INDEX IF NOT EXISTS idx_detalle_factura
ON detalle_factura(factura_id);

CREATE INDEX IF NOT EXISTS idx_detalle_producto
ON detalle_factura(producto_id);


-- =========================================================
-- CONSULTAS DE COMPROBACIÓN
-- =========================================================

SELECT *
FROM usuarios
ORDER BY id;


SELECT *
FROM clientes
ORDER BY id;


SELECT *
FROM proveedores
ORDER BY id;


SELECT *
FROM productos
ORDER BY id;


SELECT *
FROM facturas
ORDER BY id;


SELECT *
FROM detalle_factura
ORDER BY id;


-- =========================================================
-- JOIN: PRODUCTOS Y PROVEEDORES
-- =========================================================

SELECT
    p.id,
    p.nombre,
    p.categoria,
    p.descripcion,
    p.stock,
    pr.nombre AS proveedor
FROM productos AS p
LEFT JOIN proveedores AS pr
    ON p.proveedor_id = pr.id
ORDER BY p.id;


-- =========================================================
-- JOIN: FACTURAS, CLIENTES, DETALLE Y PRODUCTOS
-- =========================================================

SELECT
    f.id,
    f.numero,
    f.fecha,
    c.nombre AS cliente,
    p.nombre AS producto,
    d.cantidad,
    d.precio,
    (d.cantidad * d.precio) AS subtotal,
    f.forma_pago,
    f.pagada
FROM facturas AS f
INNER JOIN clientes AS c
    ON f.cliente_id = c.id
INNER JOIN detalle_factura AS d
    ON d.factura_id = f.id
INNER JOIN productos AS p
    ON d.producto_id = p.id
ORDER BY f.id;